import {
  beverage1,
  beverage2,
  beverage3,
  beverage4,
  beverage5,
  beverage6,
  beverage7,
  beverage8,
  burger1,
  burger2,
  burger3,
  burger4,
  burger5,
  burger6,
  burger7,
  burger8,
  promo1,
  promo2,
  review2,
  review4,
  review5,
  snack1,
  snack2,
  snack3,
  snack4,
  snack5,
  snack6,
  snack7,
  snack8,
} from "../assets/images";

export const navLinks = [
  { href: "#home", label: "Home" },
  { href: "#about-us", label: "About Us" },
  { href: "#menu", label: "Menu" },
  { href: "#review", label: "Review" },
  { href: "#contact-us", label: "Contact Us" },
];

export const categories = [
  {
    imgURL: burger1,
    title: "food",
    text: "Crispy chicken patty burger, our best seller",
    bgColor: "bg-secondaryColor",
  },
  {
    imgURL: snack1,
    title: "Snack",
    text: "Crispy fries with peri peri spice.",
    bgColor: "bg-redColor",
  },
  {
    imgURL: beverage1,
    title: "Beverage",
    text: "Our signature mango thick shake.",
    bgColor: "bg-greenColor",
  },
];

export const promos = [
  {
    imgURL: promo1,
    title: "Get a 10% Discount on Payday week",
    text: "Double up our best selling crispy veg Burger.",
  },
  {
    imgURL: promo2,
    title: "FRIENDS and Family Combo(Save upto 20%)",
    text: "Save Rs 99 Chicken Wopper + Mid Fries + Pepsi",
  },
];

export const menu = [
  {
    id: 1,
    title: "Chicken Whooper",
    category: "food",
    price: 15.99,
    img: burger1,
    desc: `Our signature whooper with 7 layers between the buns`,
  },
  {
    id: 2,
    title: "Mutton Whooper",
    category: "food",
    price: 13.99,
    img: burger2,
    desc: `Taste the fiesta in our Limited Time Mexican Mutton.`,
  },
  {
    id: 3,
    title: "Boss Whooper Mutton",
    category: "food",
    price: 6.99,
    img: burger3,
    desc: `The Biggest Whooper ever, Boss Whooper with premium buns. `,
  },
  {
    id: 4,
    title: "Panner Royal Burger",
    category: "food",
    price: 20.99,
    img: burger4,
    desc: `Thick panner patty, loads of sasus in soft masala`,
  },
  {
    id: 5,
    title: "Veg Makani Burst Burger",
    category: "food",
    price: 22.99,
    img: burger5,
    desc: `Enjoy rich makahni flavour with veg patty mix`,
  },
  {
    id: 6,
    title: "Fries King",
    category: "snacks",
    price: 18.99,
    img: snack4,
    desc: `The Perfect crispy partner`,
  },
  {
    id: 7,
    title: "Cheesy Fries",
    category: "snacks",
    price: 8.99,
    img: snack1,
    desc: `Crispy french fries, loads of cheese, yum! `,
  },
  {
    id: 8,
    title: "HashBrown",
    category: "snacks",
    price: 12.99,
    img: snack2,
    desc: `What every potato wants to be.`,
  },
  {
    id: 9,
    title: "Creamy Italian Fries",
    category: "snacks",
    price: 16.99,
    img: snack3,
    desc: "The Lip-smaking duo of creamy classic mayo ...",
  },
  {
    id: 10,
    title: "Medium Soft Drink COLA",
    category: "beverage",
    price: 16.99,
    img: beverage1,
    desc: "Our Signature Cool Drinks...!",
  },
  {
    id: 11,
    title: "Mango Thick Shake",
    category: "beverage",
    price: 16.99,
    img: beverage2,
    desc: "Our Signature Cool Drinks...!",
  },
  {
    id: 12,
    title: "Medium Soft Drink CLEAR",
    category: "beverage",
    price: 16.99,
    img: beverage3,
    desc: "Our Signature Cool Drinks...!",
  },
  {
    id: 13,
    title: "Medium Soft Drink Lemon",
    category: "beverage",
    price: 16.99,
    img: beverage4,
    desc: "Our Signature Cool Drinks...!",
  },
  {
    id: 14,
    title: "Medium Soft Drink Clear",
    category: "beverage",
    price: 16.99,
    img: beverage5,
    desc: "Our Signature Cool Drinks...!",
  },
  {
    id: 15,
    title: "Buntastic Kadhai Paneer Burger",
    category: "food",
    price: 18.99,
    img: burger7,
    desc: `Enjoy rich makahni flavour with veg patty mix`,
  },
  {
    id: 16,
    title: "Flammed Burger",
    category: "food",
    price: 30.99,
    img: burger8,
    desc: `Enjoy rich makahni flavour with veg patty mix`,
  },
  {
    id: 17,
    title: "Cheese Loaded Fries",
    category: "snacks",
    price: 20.75,
    img: snack6,
    desc: " Is it sweet, salty, spicy, tangy, or savory?",
  },
  {
    id: 18,
    title: "Indian Chaat Fries",
    category: "snacks",
    price: 10.18,
    img: snack7,
    desc: "crunchy, crispy, chewy, creamy, or flaky",
  },
  {
    id: 19,
    title: "Truffle Cheese Fries",
    category: "snacks",
    price: 26.55,
    img: snack8,
    desc: "Recommend beverages, dips, or other foods",
  },
  {
    id: 20,
    title: "Monstar",
    category: "beverage",
    price: 5.05,
    img: beverage6,
    desc: "Monstar will create Master",
  },
  {
    id: 21,
    title: "Red Bull",
    category: "beverage",
    price: 5.05,
    img: beverage7,
    desc: "Red Bull have a good and energy...",
  },
  {
    id: 22,
    title: "Fanta",
    category: "beverage",
    price: 5.05,
    img: beverage8,
    desc: "Orange Flavour Fanta was awesome.",
  },
];
